#define NORFLASH_CMD_WR_EN 0x06u

#define NORFLASH_CMD_JEDEC_ID 0x9Fu

#define NORFLASH_CMD_FAST_READ 0x0Bu

#define NORFLASH_CMD_RD_STATUS1 0x05u

#define NORFLASH_CMD_CHIP_ERASE 0xC7u

#define NORFLASH_CMD_PAGE_PROG 0x02u

#define NORFLASH_BUSSY_BIT 0u
#define NORFLASH_WEL_BIT 1u

#define NORFLASH_FAST_READ_CMDBUF_LEN 5 //1 cmd + 3 add + 1 dummy